name: covid19_tracker
description: application de tracking d'informations concernant le COVID-19


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.10.0
  auto_size_text: ^2.1.0
  line_awesome_flutter: ^1.0.1
  equatable: ^1.2.5
  intl: ^0.16.0
  http: ^0.12.1
  url_launcher: ^5.4.5
  image_picker: ^0.6.7+4
  flutter_gifimage: ^1.0.1
  path_provider: ^1.6.21
  sqflite: ^1.3.1
  path: ^1.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: sansita
      fonts:
        - asset: assets/fonts/Sansita.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 200
          style: italic
          
